apiVersion: v0.1.0
envs:
- name: dev-environment
  path: .xlr8s/envs/dev-environment/env.yaml
git:
  repoUrl: git@github.com:xi3007-prajpal/testing-resource-logs.git
  revision: main
modules:
  k8stools:
  - module: git@github.com:xebiaww-apps/helm-xebia-opa-gatekeeper.git
    ref:
      tag: v0.4.3
  - module: git@github.com:xebiaww-apps/helm-xebia-opa-gatekeeper-constraints.git
    ref:
      tag: v0.1.0
  - module: xebia-istioctl
    ref:
      tag: 1.13.3
  - module: git@github.com:xebiaww-apps/helm-xebia-istio-policies.git
    ref:
      tag: v0.1.1
  - module: git@github.com:xebiaww-apps/helm-xebia-prometheus.git
    ref:
      tag: v0.1.1
  - module: git@github.com:xebiaww-apps/helm-xebia-kiali.git
    ref:
      tag: v0.4.0
  - module: git@github.com:xebiaww-apps/helm-xebia-metrics-server.git
    ref:
      tag: v0.2.0
  - module: git@github.com:xebiaww-apps/helm-xebia-secrets-store-csi-driver.git
    ref:
      tag: v0.3.0
  - module: git@github.com:xebiaww-apps/helm-xebia-fluent-bit.git
    ref:
      tag: v0.4.3
  terraform:
  - module: git@github.com:xebiaww-apps/terraform-aws-xebia-eks.git
    ref:
      tag: v1.4.0
name: event-logs-testing-8266
vars:
  apps: null
  policy: null
